---
- hosts: localhost
  connection: local
  remote_user: root
  vars_prompt:
    - name: "user_email"
      prompt: "Email (optional)"
      private: no
    - name: "user_name"
      prompt: "FirstName LastName (optional)"
      private: no
  vars:
    github_access_token: ""
    user_workspace: "{{ansible_env.HOME}}/Workspace"
    ssh_id_rsa: "{{ansible_env.HOME}}/.ssh/id_rsa"
    ssh_id_rsa_pub: "{{ssh_id_rsa}}.pub"
    # nodejs_package_version: '8'
    java_package_version: '8'
    atom_package_state: absent

    composer_packages: []
    gem_packages: []
    pip_packages: []

    homebrew_packages:
      - cocoapods

    homebrew_cask_packages:
      - skitch
      - google-drive-file-stream
      - mysqlworkbench
      - apache-couchdb

    vscode_extensions:
      - EditorConfig.EditorConfig
      - Shan.code-settings-sync
      - eamodio.gitlens
      - ms-vsliveshare.vsliveshare
      - MS-CEINTL.vscode-language-pack-fr

    appstore_signin_dialog: yes
    appstore_installed_apps:
      - { id: 497799835, name: "Xcode" }

    npm_packages:
      - name: yarn
      - name: react-native-cli

  roles:
    - { role: ansible-role-buildessential, become: true, ignore_errors: yes, tags: ['always'] }
    - { role: ansible-role-zsh, become: true, ignore_errors: yes, tags: ['console'] }
    - { role: ansible-role-git, become: true, ignore_errors: yes, tags: ['scm'] }
    - { role: ansible-role-mercurial, become: true, ignore_errors: yes, tags: ['scm'] }
    - { role: ansible-role-atom, become: true, ignore_errors: yes, tags: ['ide'] }
    - { role: ansible-role-slack, become: true, ignore_errors: yes, tags: ['com'] }
    - { role: ansible-role-docker, become: true, ignore_errors: yes }
    - { role: ansible-role-virtualbox, become: true, ignore_errors: yes }
    - { role: ansible-role-nodejs, become: true, ignore_errors: yes, tags: ['js'] }
    - { role: ansible-role-java, become: true, ignore_errors: yes, tags: ['java', 'android'] }
    - { role: ansible-role-visualstudiocode, become: true, ignore_errors: yes, tags: ['ide'] }
    - { role: ansible-role-androidstudio, become: true, ignore_errors: yes, tags: ['ide', 'android'] }
    - { role: ansible-role-androidtools, become: true, ignore_errors: yes, tags: ['ide', 'android'] }
    - { role: ansible-role-composer, become: true, ignore_errors: yes, tags: ['php'] }
    - { role: ansible-role-react-native-debugger, become: true, ignore_errors: yes, tags: ['ios', 'android', 'react'] }
    - { role: ansible-role-chromedriver, become: true, ignore_errors: yes }
    - { role: ansible-role-sketch, become: true, ignore_errors: yes, tags: ['design'] }
    - { role: ansible-role-notion, become: true, ignore_errors: yes, tags: ['com'] }
    - { role: ansible-role-term, become: true, ignore_errors: yes, tags: ['console'] }
    - { role: ansible-role-watchman, become: true, ignore_errors: yes, tags: ['console'] }
    # - { role: ansible-role-appstore, ignore_errors: yes, when: appstore_installed_apps, tags: ['appstore'] }
    - { role: ansible-role-postman, become: true, ignore_errors: yes, tags: ['api', 'web'] }

  tasks:

    - name: Install global Composer packages.
      composer:
        command: "{{ (item.state | default('present') == 'absent') | ternary('remove', 'require') }}"
        arguments: "{{ item.name | default(item) }} {{ item.version | default('@stable') }}"
        # Ansible 2.4 supports `global_command` making `working_dir` optional.
        working_dir: "{{ lookup('env', 'COMPOSER_HOME') | default('~/.composer', true) }}"
      with_items: "{{ composer_packages }}"

    - name: Check if php5 directory exists.
      stat:
        path: /usr/local/php5/
      register: php5_dir

    - name: Install PHP 5.6 in /usr/local/php5/
      shell: curl -s https://php-osx.liip.ch/install.sh | bash -s force 5.6
      args:
        warn: false
      when:
        - ansible_os_family == 'Darwin'
        - not php5_dir.stat.exists

    - name: Install global NPM packages.
      npm:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        global: yes
        executable: "{{ item.executable | default(omit) }}"
      with_items: "{{ npm_packages }}"
      when: npm_packages

    - name: Install global Pip packages.
      pip:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        executable: "{{ item.executable | default(omit) }}"
      with_items: "{{ pip_packages }}"
      when: pip_packages

    - name: Install global Ruby gems.
      gem:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
        user_install: no
        executable: "{{ item.executable | default(omit) }}"
      with_items: "{{ gem_packages }}"
      when: gem_packages

    - name: Include specific OSX configuration
      include: "main.osx.yml"
      when: ansible_os_family == 'Darwin'

    - name: Add SSH Known Hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item) }}"
      with_items:
        - github.com
        - bitbucket.org
      become: true
      ignore_errors: yes

    - name: Ensure ~/Workspace exists
      file: >
          state=directory
          name="{{ user_workspace }}"
          owner={{ ansible_env.USER }}

    - name: Install VSCode extensions
      vscode:
        name: "{{item}}"
        state: present
      with_items: "{{ vscode_extensions }}"
      tags: ['ide', 'vscode']
      ignore_errors: yes

    - name: Set GIT diff
      git_config:
        name: diff.tool
        scope: global
        value: "vscode"
      become: false
      tags: ['git']

    - name: Set GIT code.editor
      git_config:
        name: core.editor
        scope: global
        value: "{{ visualstudiocode_git_editor }}"
      become: false
      tags: ['git']

    - name: Set GIT user.email
      git_config:
        name: user.email
        scope: global
        value: "{{ user_email }}"
      become: false
      when: user_email|bool == true
      tags: ['git']

    - name: Set GIT user.name
      git_config:
        name: user.name
        scope: global
        value: "{{ user_name }}"
      become: false
      when: user_name|bool == true
      tags: ['git']

    - name: Create SSH key
      command: >
          ssh-keygen -t rsa -b 4096 -C "{{ansible_env.USER}}@{{ inventory_hostname_short }}" -N '' -o -f {{ ssh_id_rsa }}
          creates={{ ssh_id_rsa_pub }}

    - name: Read SSH public key to authorize
      shell: cat {{ssh_id_rsa_pub}}
      register: ssh_pub_key
